# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zaferon Grill
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Mediterranean-Inspired American Bistro.
#baseurl:  /zaferonGrill # the subpath of your site, e.g. /blog
url: http://zaferongrill.com
#twitter_username: jekyllrb
#github_username:  jekyll
instagram_username: zaferongrill
facebook_username: zaferongrill

# Build settings
markdown: kramdown
encoding: utf-8

# Server Config options
livereload: true    # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port